.github/linters/.golangci.yml, .github/workflows/testing.yml
=> Use super-linter for linting

README.md, job.go, worker.go, worker_option.go, worker_option_test.go, worker_test.go
Addresses https://github.com/vgarvardt/gue/issues/41
=> Added job lifecycle hooks

.github/linters/.sqlfluff, .github/linters/.yaml-lint.yml, .github/workflows/base-lint.yml, .github/workflows/codeql-analysis.yml, .github/workflows/pr-lint.yml, client.go, client_test.go, schema.sql, worker.go
Based on the full scan results - https://github.com/vgarvardt/gue/runs/6061455769?check_suite_focus=true
=> Tuned linter rules and fixed existing issues

README.md, adapter/gopgv10/db.go, adapter/libpq/db.go, adapter/pgxv4/db.go, adapter/pgxv5/db.go, adapter/testing/all.go, adapter/testing/gopgv10.go, adapter/testing/libpq.go, adapter/testing/pgxv4.go, adapter/testing/pgxv5.go, adapter/zap/logger.go, adapter/zap/logger_test.go, client.go, client_option.go, client_option_test.go, client_test.go, doc.go, enqueue_test.go, go.mod, go.sum, job.go, worker.go, worker_option.go, worker_option_test.go, worker_test.go
Breaking changes are coming...
=> Bumped package to v4

worker.go, worker_test.go
Major version update - time to cleanup stuff marked as deprecated.
=> Removed deprecated Worker.Start and WorkerPool.Start

CHANGELOG.md, adapter/db.go, adapter/gopgv10/db.go, adapter/libpq/db.go, adapter/logger.go, adapter/pgxv4/db.go, adapter/pgxv5/db.go, adapter/zap/logger_test.go
=> Addec changelog and replaced interface with any

adapter/db.go, adapter/gopgv10/db.go, adapter/libpq/db.go, adapter/pgxv4/db.go, adapter/pgxv5/db.go, doc.go
=> Added connection to db adapter and all implementations

.github/linters/.jscpd.json, adapter/testing/mock.go
Bundle testing stuff right in the package.
=> Added mocks db adapters

.github/workflows/codeql-analysis.yml
Keep things more or less up to date
=> Updated CodeQL action version

go.mod, worker.go
Maybe will help with https://github.com/vgarvardt/gue/issues/64
=> Log error in case of panicked job stacktrace building failure

client.go, client_option_test.go, go.mod, go.sum, worker.go, worker_option_test.go
=> Bumped OTel metrics to 0.31

ctx.go, ctx_test.go, worker.go, worker_test.go
Addresses https://github.com/vgarvardt/gue/issues/88
=> Added index information to the worker ctx in the pool

.github/actions/setup-deps/action.yaml, .github/workflows/lint.yml, doc.go, worker.go
Trying to fix https://github.com/vgarvardt/gue/actions/runs/3184831864
=> Setup go for linting

.editorconfig, worker.go, worker_option.go, worker_option_test.go, worker_test.go
Addresses https://github.com/vgarvardt/gue/issues/116
=> Added graceful shutdown option

worker_test.go
Refs https://github.com/vgarvardt/gue/issues/125
=> Covered panic logging with the test

.github/linters/.markdown-lint.yml, CHANGELOG.md, backoff_test.go, client_test.go, enqueue_test.go, error.go, error_test.go, go.mod, job.go, worker.go, worker_test.go
Refs https://github.com/vgarvardt/gue/issues/124
PR introduces public API breaking changes, so this change will be released as the major update together with some other breaking changes.
=> Allow controlling job reschedule/discard using typed errors

.github/linters/.golangci.yml, CHANGELOG.md, README.md, adapter/libpq/db.go, adapter/pgxv4/db.go, adapter/pgxv5/db.go, adapter/testing/all.go, adapter/testing/libpq.go, adapter/testing/mock.go, adapter/testing/pgxv4.go, adapter/testing/pgxv5.go, adapter/zap/logger.go, adapter/zap/logger_test.go, backoff_test.go, client.go, client_option.go, client_option_test.go, client_test.go, doc.go, docker-compose.yml, enqueue_test.go, error_test.go, go.mod, job.go, schema.sql, worker.go, worker_option.go, worker_option_test.go, worker_test.go
Solves https://github.com/vgarvardt/gue/issues/105
=> Support byte-encoded job arguments, not only JSON

_example/outbox-worker-kafka/go.mod, go.mod
=> build: bump min golang version to 1.19

worker.go, worker_option.go, worker_option_test.go
Addresses https://github.com/vgarvardt/gue/issues/185
Based on https://github.com/vgarvardt/gue/pull/186
=> feat: added support for WorkOne no-job tracing span

client.go
I have a use-case for this method, I run a multi instance system where some operation can happen on different instances at the same time. I want to use this gue package to make sure followup action or only executed one single time. I can calculate a ulid for my action and use the `EnqueueWithID` to guarantee those action are not running in parallel on different instances.
=> add EnqueueWithID method so the client can control the id

client.go, enqueue_test.go
=> feat: add EnqueueTxWithID 
